name: Release Management

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

# Only run in the template repository
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.repository == 'azure/osdu-spi'

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5

      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}

      - name: Generate Release PR
        uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c  # v4
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .release-please-config.json
